### ISSUE TITLE
Deploy app to Heroku

### ISSUE THREAD

**Issue by jannis-kiriasis** [jannis-kiriasis/the-checklistar#2]
**TASKS:**

Create Heroku app:
- [ ] Create Heroku app

Attach Database:
- [ ] Attach the database ElephantSQL (Add config vars to Heroku, create env.py and set env variables + secret key in Gitpod)

Prepare environment variables and settings.py:
- [ ] Setup: env variables, secret key, database in settings.py

Setup Cloudinary, media static and templates folders:
- [ ] Setup Cloudinary
- [ ] Setup templates directory
- [ ] Allow host Heroku
- [ ] Create media, static and templates folders

- [ ] Create Procfile

- [ ] Commit and push changes
- [ ] Deploy on Heroku
