### ISSUE TITLE
USER STORY: Create a project

### ISSUE THREAD

**Issue by jannis-kiriasis** [jannis-kiriasis/the-checklistar#3]
As a **project owner** I can **create a project and append a pdf to be reviewed or write a project description* so that **the workflow can be used for document approvals or as a workflow management software**.

**Tasks:**

- [ ] Create a project creation template with a form that includes the project owner, title, description, document, date created, due date, approver name and dept.
- [ ] Create a model for Project, including URL and view
- [ ] Create a model for UserProfile which can be approver either and project owner including their department
